### PR TITLE
Attendee enter fix

### LINKED ISSUE #502: Enter in new attendee field closes sidebar

### PR DESCRIPTION
**Pull request by platypro**
Fixes #502. The enter key should be a little more predictable. Enter by itself will never close the dialog or apply anything, but Ctrl+Enter does. Now when the enter key is pressed while adding an attendee, it adds it instead of closing (and applying) the event.

### CODE REVIEW

**Comment by georgehrke** [comment]
@platypro Thx a lot for your pull-request! 
Can you please sign off your commits?

**Comment by georgehrke** [comment]
@jancborchardt What do you think about the `Ctrl` + `Enter`?

**Comment by georgehrke** [comment]
- [ ] Test if it works with `CMD` + `Enter` too (for macs)

**Comment by jancborchardt** [comment]
Well, enter in the new attendee field should not close the sidebar / dialog at all either. :) In this case it seems that enter and ctrl+enter should do the same thing?

**Comment by georgehrke** [comment]
> Well, enter in the new attendee field should not close the sidebar / dialog at all either. :) In this case it seems that enter and ctrl+enter should do the same thing?

@jancborchardt The idea here is that you can only close the dialog with CTRL+C / ⌘+C

Enter will only work for the field you are currently editing.

**Comment by jancborchardt** [comment]
Ctrl-C is a shortcut for copying, not closing. :)

- Enter should save but not close (as does this pull request, correct @platypro?)
- Ctrl-Enter should save and closr
- Esc should close and not save
- Ctrl-C should not close ;)

**Comment by georgehrke** [comment]
I'm sorry, i obviously didnt mean CTRL+C but CTRL+Enter

**Comment by platypro** [comment]
@jancborchardt The idea was that enter should not save anything when the user was probably intending to do something else, such as adding a new attendee. If this pull request does otherwise then that was not what I intended.

**Comment by jancborchardt** [comment]
@platypro well, enter does »save« in the sense that it adds a new attendee, right? I basically agree with what this pull request does design-wise. :) If it works then go ahead with it @georgehrke

**Comment by platypro** [comment]
@jancborchardt If thats what you were implying then its working how I expected it to.

**Comment by georgehrke** [comment]
@platypro Can you please modify the template of the events editor popover as well, so we have the same CTRL / CMD + ENTER behavior there as well :) 
THX!

**Comment by georgehrke** [comment]
> Ctrl-Enter should save and close

That's not the case yet. It only saves the event, but doesn't add the attendee.

**Comment by platypro** [comment]
I see what you mean. Would it also be acceptable for a notification to show if an attendee is added? It might not be obvious to everyone.

File: js/app/controllers/editorcontroller.js [hunk 1]
```diff
@@ -121,6 +121,14 @@ app.controller('EditorController', ['$scope', 'TimezoneService', 'AutoCompletion
 			});
 		};
 
+		$scope.keypress = function(event) {
+			var code = event.keyCode || event.which;
+			if(event.ctrlKey===true && code === 13) {
```
Comment (georgehrke) [inline js/app/controllers/editorcontroller.js]: Can you please use `event.metaKey`. Then it will also work on Macs. :)

https://api.jquery.com/event.metakey/

**Comment by georgehrke** [comment]
And please remember to sign your commits :) 

Then this is ready to go

File: js/app/controllers/editorcontroller.js [hunk 2]
```diff
@@ -123,8 +123,8 @@ app.controller('EditorController', ['$scope', 'TimezoneService', 'AutoCompletion
 
 		$scope.keypress = function(event) {
 			var code = event.keyCode || event.which;
-			if(event.ctrlKey===true && code === 13) {
-				$scope.$broadcast('save-contents');
+			if((event.metaKey===true || event.ctrlKey===true) && code === 13) {
```
Comment (georgehrke) [inline js/app/controllers/editorcontroller.js]: `if(event.metaKey===true && code === 13) {` should be just fine.

Meta-Key is true for CTRL on Windows / Linux and CMD on Mac :)
https://api.jquery.com/event.metakey/

File: js/app/controllers/editorcontroller.js [hunk 3]
```diff
@@ -123,8 +123,8 @@ app.controller('EditorController', ['$scope', 'TimezoneService', 'AutoCompletion
...
+			  $scope.$broadcast('save-contents');
```
Comment (georgehrke) [inline js/app/controllers/editorcontroller.js]: Please fix the indentation back to tabs

File: js/app/controllers/editorcontroller.js (hunk 2 above)
Comment (georgehrke) [reply js/app/controllers/editorcontroller.js]: and please add spaces on the left side: `event.metaKey === true`, not `event.metaKey===true `

Comment (georgehrke) [reply js/app/controllers/editorcontroller.js]: Sorry, it doesn't map to CTRL on Windows, it maps to the windows key.
My fault

**Comment by georgehrke** [comment]
@platypro Thanks a lot for this pull-request! :)
