### PR TITLE
Fix locale / language bug

### LINKED ISSUE #920: Locale and language conflicts
### Steps to reproduce
1. Install latest calendar app
2. Have the Nextcloud instance language set to English (US) (in Settings -> Personal Info)
3. Have the Nextcloud instance locale set to a non English speaking region, for example German (Germany) (in Settings -> Personal Info)

### Expected behavior
Calendar time and date should change, leaving the language settings of days intact. Order of days should either be set by the locale, or, preferably, be selected by the user separately from locale and language settings.

### Actual behavior
The language of the calendar is changed by the locale change (day names, months, etc.). Also, days are ordered by what is general practice in the selected locale (this, however, makes life more difficult for Americans living in Europe, or vice versa).

### Server configuration
I have no access to the information relevant to this section. Behavior described above spotted on a demo server running Nextcloud 14.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64400780-locale-and-language-conflicts?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by georgehrke**
Fixes #920 

On top of that, it makes sure that all date pickers we use are properly localised.

### CODE REVIEW

File: src/components/Shared/DatePicker.vue [hunk 1]
```diff
@@ -0,0 +1,228 @@
...
+			parts.push(moment.localeData(this.locale).longDateFormat('L'))
+
+			if (this.isAllDay) {
+				return parts.join('')
+			}
+
+			parts.push(
+				' [',
+				this.$t('calendar', 'at'),
+				'] ',
```
Comment (tcitworld) [inline src/components/Shared/DatePicker.vue]: Why not just `$t('calendar', ' [at] ')` or at least something like `$t('calendar', '%sat%s', ' [', '] ')`. It would give translators more context.

File: src/components/Shared/DatePicker.vue [hunk 2]
```diff
@@ -0,0 +1,228 @@
...
+		/**
+		 * Formats the date string
+		 *
+		 * @returns {String}
+		 */
+		format() {
+			const parts = []
+
+			if (this.prefix) {
+				parts.push('[', this.prefix, '] ')
```
Comment (tcitworld) [inline src/components/Shared/DatePicker.vue]: In the same way as the comment below, it would be nice if the values for `prefix` were constants (`PREFIX_FROM`, `PREFIX_ON`,...) and the translation happened here.

File: src/components/Shared/TimePicker.vue [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+		/**
+		 * Formats the date string
+		 *
+		 * @returns {String}
+		 */
+		format() {
+			const parts = []
+
+			if (this.prefix) {
+				parts.push('[', this.prefix, '] ')
```
Comment (tcitworld) [inline src/components/Shared/TimePicker.vue]: Same applies here.

**Comment by georgehrke** [comment]
Important point with the translations. :) 

I changed it: https://github.com/nextcloud/calendar/pull/1583/files#diff-17a376f9ab3bb50d897c5789825e077cR152-R180

**Comment by georgehrke** [comment]
Failure unrelated: https://travis-ci.org/nextcloud/calendar/builds/602966284?utm_medium=notification&utm_source=github_status
