### PR TITLE
Fix parsing of First day parameter

### LINKED ISSUE #1944: Navigation and Display issue in day view
There are two serious issues with the Day View on the calendar.
1. Clicking the "Next Day" button does not advance to the next date. 
2. The Date picker label that is between the back and next button is off by one, except when showing  "Today". For example, if the date selected is "Jan 30, 2020", the label reads "Jan 29, 2020"
Screen Shot 2020-02-01 at 9 37 09 AM

These issues have been present since upgrading to Calendar 2.0.1, and are not present in 1.7.1. I have tested the issue in multiple browsers and multiple nextcloud server installations. 

Thanks.

### Steps to reproduce
1. Open Calendar.
2. Click the Next Day button more than once
3. Observe label and URL bar

### Expected behaviour
- The Label should match the current url 
- The date should advance one day for each click of the Next Day button 

### Actual behaviour
- The Label is one day less than the current day in the url bar 
- The first click changes the URL from **timeGridDay/now** to **timeGridDay/2020-02-02**, further clicks do nothing

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
This has been observed on Windows 10 with Chrome and Edge as well. 

**Browser:** (e.g. Firefox 48)
Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Operating system:** (e.g. Arch Linux)
Mac OS 10.14.6

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 9.11 

**Web server:** (e.g. Apache, Nginx,...)
nginx/1.12.1

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
10.1.41-MariaDB-0+deb9u1

**PHP version:** (e.g. 7.0.3)
7.3.14

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
17.0.2

**Updated from an older installed version or fresh install:**
Updated since v14 or 15, I forget 

**List of activated apps:**
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - deck: 0.8.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.1.2
  - music: 0.12.1
  - nextcloud_announcements: 1.6.0
  - notes: 3.1.1
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - onlyoffice: 4.1.4
  - password_policy: 1.7.0
  - passwords: 2020.2.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.2
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.1.2
  - unsplash: 1.1.5
  - updatenotification: 1.7.0
  - user_usage_report: 1.1.2
  - viewer: 1.2.0
  - workflowengine: 1.7.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**
{
    "system": {
        "debug": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.ismay.ca"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.ismay.ca",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_template_class": "\\OC\\Mail\\MyEMailTemplate",
        "maintenance": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "twofactor_admin",
            "spreed"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.10.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "238"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.1.8",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installedat": "1523578967.7588",
            "lastcron": "1580579102",
            "lastupdateResult": "{\"version\":\"17.0.3.1\",\"versionstring\":\"Nextcloud 17.0.3\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-17.0.3.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/17\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=17.0.3\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "1580579147",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "9a8e257dba25d9fa2c2793db9cc84eaa",
            "theming.variables": "9a8e257dba25d9fa2c2793db9cc84eaa",
            "updater.secret.created": "1580495661",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "no",
            "installed_version": "6.0.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.13.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "dav"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "files_reader": {
            "enabled": "no",
            "installed_version": "1.2.3",
            "types": "filesystem"
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.1",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.4.0",
            "types": ""
        },
        "keeporsweep": {
            "enabled": "no",
            "installed_version": "0.2.1",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": ""
        },
        "music": {
            "enabled": "yes",
            "installed_version": "0.12.1",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "3.1.1",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "enabled": "yes",
            "installed_version": "4.1.4",
            "types": "filesystem"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "installed_version": "1.7.0",
            "types": ""
        },
        "passwords": {
            "SSEv1ServerKey": "***REMOVED SENSITIVE VALUE***",
            "backup\/timestamp": "1564652701",
            "backups\/moved": "yes",
            "deleted_users": "[]",
            "enabled": "yes",
            "installed_version": "2020.2.0",
            "legacy_api_checkpoint": "1580326202",
            "legacy_last_used": "1580505293",
            "migration\/customFields": "2020.2.0",
            "migration\/hibp": "1",
            "passwords\/localdb\/type": "hibp",
            "survey\/server\/mode": "2",
            "survey\/server\/notification": "1562868002",
            "survey\/server\/week": "05",
            "types": "",
            "users\/deleted": "[]"
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "prevent_group_restriction"
        },
        "quota_warning": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "7.0.2",
            "project_access_invalidated": "1",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "last_report": "{\"id\":\"oc0zlt5zkzv1\",\"items\":[[\"server\",\"version\",\"17.0.2.1\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"none\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"yes\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.3.13\"],[\"php\",\"memory_limit\",-1],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.1.41\"],[\"database\",\"size\",93388800],[\"apps\",\"accessibility\",\"1.3.0\"],[\"apps\",\"activity\",\"2.10.1\"],[\"apps\",\"admin_audit\",\"1.7.0\"],[\"apps\",\"bruteforcesettings\",\"1.4.0\"],[\"apps\",\"calendar\",\"1.7.2\"],[\"apps\",\"cloud_federation_api\",\"1.0.0\"],[\"apps\",\"comments\",\"1.7.0\"],[\"apps\",\"contacts\",\"3.1.6\"],[\"apps\",\"dashboard\",\"disabled\"],[\"apps\",\"dav\",\"1.13.0\"],[\"apps\",\"deck\",\"0.7.0\"],[\"apps\",\"federatedfilesharing\",\"1.7.0\"],[\"apps\",\"federation\",\"1.7.0\"],[\"apps\",\"files\",\"1.12.0\"],[\"apps\",\"files_external\",\"1.8.0\"],[\"apps\",\"files_pdfviewer\",\"1.6.0\"],[\"apps\",\"files_reader\",\"disabled\"],[\"apps\",\"files_rightclick\",\"0.15.1\"],[\"apps\",\"files_sharing\",\"1.9.0\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.7.0\"],[\"apps\",\"files_versions\",\"1.10.0\"],[\"apps\",\"files_videoplayer\",\"1.6.0\"],[\"apps\",\"firstrunwizard\",\"2.6.0\"],[\"apps\",\"gallery\",\"18.4.0\"],[\"apps\",\"keeporsweep\",\"disabled\"],[\"apps\",\"logreader\",\"2.2.0\"],[\"apps\",\"lookup_server_connector\",\"1.5.0\"],[\"apps\",\"mail\",\"0.21.1\"],[\"apps\",\"music\",\"0.12.1\"],[\"apps\",\"nextcloud_announcements\",\"1.6.0\"],[\"apps\",\"notes\",\"3.1.1\"],[\"apps\",\"notifications\",\"2.5.0\"],[\"apps\",\"oauth2\",\"1.5.0\"],[\"apps\",\"onlyoffice\",\"4.0.0\"],[\"apps\",\"password_policy\",\"1.7.0\"],[\"apps\",\"passwords\",\"2020.1.0\"],[\"apps\",\"privacy\",\"1.1.0\"],[\"apps\",\"provisioning_api\",\"1.7.0\"],[\"apps\",\"quota_warning\",\"1.6.0\"],[\"apps\",\"recommendations\",\"0.5.0\"],[\"apps\",\"serverinfo\",\"1.7.0\"],[\"apps\",\"sharebymail\",\"1.7.0\"],[\"apps\",\"spreed\",\"7.0.2\"],[\"apps\",\"support\",\"1.0.1\"],[\"apps\",\"survey_client\",\"1.5.0\"],[\"apps\",\"systemtags\",\"1.7.0\"],[\"apps\",\"tasks\",\"0.11.3\"],[\"apps\",\"text\",\"1.1.1\"],[\"apps\",\"theming\",\"1.8.0\"],[\"apps\",\"twofactor_admin\",\"disabled\"],[\"apps\",\"twofactor_backupcodes\",\"1.6.0\"],[\"apps\",\"twofactor_totp\",\"4.1.2\"],[\"apps\",\"unsplash\",\"1.1.4\"],[\"apps\",\"updatenotification\",\"1.7.0\"],[\"apps\",\"user_usage_report\",\"1.1.2\"],[\"apps\",\"viewer\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"1.7.0\"],[\"stats\",\"num_files\",133767],[\"stats\",\"num_users\",5],[\"stats\",\"num_storages\",7],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",6],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",2],[\"stats\",\"num_comment_markers\",1],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",6],[\"files_sharing\",\"num_shares_user\",4],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",2],[\"files_sharing\",\"num_shares_link_no_password\",2],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_0_1\",\"1\"],[\"files_sharing\",\"permissions_3_1\",\"2\"],[\"files_sharing\",\"permissions_0_17\",\"1\"],[\"files_sharing\",\"permissions_0_19\",\"1\"],[\"files_sharing\",\"permissions_0_31\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1579112103",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.11.3",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "9",
            "color": "#0B3B01",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "name": "MyCloud",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_admin": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "types": ""
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "4.1.2",
            "types": ""
        },
        "unsplash": {
            "enabled": "yes",
            "installed_version": "1.1.5",
            "types": "",
            "unsplash\/style\/header": "0"
        },
        "updatenotification": {
            "bruteforcesettings": "1.4.0",
            "calendar": "2.0.1",
            "contacts": "3.1.8",
            "core": "17.0.3.1",
            "dashboard": "5.0.0",
            "deck": "0.6.6",
            "enabled": "yes",
            "files_pdfviewer": "1.2.1",
            "files_rightclick": "0.15.1",
            "installed_version": "1.7.0",
            "mail": "1.1.2",
            "music": "0.12.0",
            "notes": "3.1.1",
            "onlyoffice": "4.1.4",
            "passwords": "2020.2.0",
            "spreed": "7.0.2",
            "twofactor_admin": "0.2.1",
            "twofactor_totp": "4.1.2",
            "types": "",
            "unsplash": "1.1.5",
            "update_check_errors": "0",
            "user_usage_report": "1.1.1"
        },
        "user_usage_report": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        }
    }
}
#### Web server error log (e.g. /var/log/apache)
Not Available

#### Log file (data/nextcloud.log)
Not Available

#### Browser log
JQMIGRATE: Migrate is installed, version 1.4.1
main.js:1095 oc_config is deprecated: use OC.config instead
He @ main.js:1095
calendar.js:2 Proxying an event bus of version 0.2.1 with 1.1.2
e @ calendar.js:2
main.js:1095 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
He @ main.js:1095
DevTools failed to parse SourceMap: https://cloud.ismay.ca/core/js/dist/main.js.map
DevTools failed to parse SourceMap: https://cloud.ismay.ca/core/js/dist/share_backend.js.map
DevTools failed to parse SourceMap: https://cloud.ismay.ca/apps/notifications/js/notifications.js.map
DevTools failed to parse SourceMap: https://cloud.ismay.ca/apps/files_videoplayer/js/main.js.map
DevTools failed to parse SourceMap: https://cloud.ismay.ca/apps/calendar/js/calendar.js.map

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #1944 

This fixes an issue with parsing the first day parameter.
The problem is that `new Date()` parsed the parameter as UTC, because it looked like an ISO string.

Resulting in:
`const d1 = new Date('2020-02-16')`
`Sat Feb 15 2020 16:00:00 GMT-0800 (Pacific Standard Time)`

This PR parses the first day parameter manually.
Turning `2020-02-26` into `Wed Feb 26 2020 00:00:00 GMT-0800 (Pacific Standard Time)`

### CODE REVIEW

File: src/utils/date.js [hunk 1]
```diff
@@ -62,7 +62,13 @@ export function getDateFromFirstdayParam(firstDayParam) {
 		return dateFactory()
 	}
 
-	return new Date(firstDayParam)
+	const [year, month, date] = firstDayParam.split('-')
+		.map((str) => parseInt(str, 10))
```
Comment (tcitworld) [inline src/utils/date.js]: No handling of bad value for `firstDayParam` (not number for instance) ?

Comment (georgehrke) [reply src/utils/date.js]: How should we handle that case?
Just default to today and log an error message?

Comment (tcitworld) [reply src/utils/date.js]: Seems fine to me. :+1:
