### PR TITLE
fix(rtl): align event title

### LINKED ISSUE #6403: [RTL] close button/actions should go left
### Steps to reproduce

Image

### Expected behavior

Good ux

### Actual behavior

bad ux 

### Mail app version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

_No response_

### LINKED ISSUE #6404: [RTL] Align event  title
### Steps to reproduce

Image

### Expected behavior

Good design

### Actual behaviour

Bad design 

### Calendar app version

_No response_

### CalDAV-clients used

_No response_

### Browser

_No response_

### Client operating system

_No response_

### Server operating system

_No response_

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

_No response_

### Updated from an older installed version or fresh install

None

### List of activated apps

_No response_

### Nextcloud configuration

_No response_

### Web server error log

_No response_

### Log file

_No response_

### Browser log

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
fix #6404
fix #6403

| b | a |
|--------|--------|
| image | image |

### CODE REVIEW

File: src/views/EditSimple.vue [hunk 1]
```diff
@@ -250,6 +251,14 @@ export default {
 			return this.isVisible || this.widgetEventDetailsOpen
 		},
 
+		topActionsClass() {
+			return {
+				'event-popover__top-actions': true,
```
Comment (DorraJaouad) [inline src/views/EditSimple.vue:256]: You can keep it static `class="event-popover__top-actions"` and keep the directions classes here.

**Review by DorraJaouad — APPROVED** [review]
Title has correct position regardless of user input language 👍🏻
Should the same be applied for links ?
image

**Review by miaulalala — APPROVED** [review]

**Comment by hamza221** [comment]
> Title has correct position regardless of user input language 👍🏻 Should the same be applied for links ? image

That's a separate problem 😢
