### PR TITLE
Fix view switching on creating new events

### LINKED ISSUE #3522: clicking on `New event` button in today view switches view to month view
Just reproduced on c.nc.c

### PR DESCRIPTION
**Pull request by st3iny**
Fix #3522

### CODE REVIEW

File: src/router.js [hunk 1]
```diff
@@ -107,6 +107,10 @@ const router = new Router({
 			path: '/new',
 			redirect: () => `/${getInitialView()}/now/new/${getPreferredEditorRoute()}/0/${getDefaultStartDateForNewEvent()}/${getDefaultEndDateForNewEvent()}`,
```
Comment (tcitworld) [inline src/router.js:108]: I think something similar to the following might be better instead of duplicating the route (didn't test).

```suggestion
			path: '/new/:view?',
			redirect: (to) => `/${to.params.view || getInitialView()}/now/new/${getPreferredEditorRoute()}/0/${getDefaultStartDateForNewEvent()}/${getDefaultEndDateForNewEvent()}`,
```

Comment (st3iny) [reply src/router.js:108]: That's a good idea. Thanks!

**Review by ChristophWurst — APPROVED** [review]

**Review by tcitworld — APPROVED** [review]
Code looks good

**Comment by szaimen** [comment]
🎉
