### PR TITLE
Fix: Not possible to close Event when Calendar is embedded into Collective

### LINKED ISSUE #7113: Smart picker calendar impossible to leave the appointment window
**Describe the bug**
In a 

**To Reproduce**

1. Have an integrated calendar to text with some appointments
2. Click on an appointment
3. try to exit

**Expected behavior**

**Screenshots**

Image

**Server details:**
- Nextcloud version: 31.0.5
- PHP Version: [e.g. 8.2]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome]
 - Browser version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

### PR DESCRIPTION
**Pull request by Koc**
Closes #7113

### CODE REVIEW

**Comment by SebastianKrupinski** [comment]
Hi @Koc

Thank you for the PR! Can you also update the description of the event with GH ticket this resolves. Thank you

File: src/mixins/EditorMixin.js [hunk 1]
```diff
@@ -404,7 +405,7 @@ export default {
 		 */
 		closeEditor() {
 			if (this.isWidget) {
-				this.calendarsStore.closeWidgetEventDetails()
+				this.widgetStore.closeWidgetEventDetails()
```
Comment (Koc) [inline src/mixins/EditorMixin.js:408]: Is it possible somehow to detect such errors on compile/lint step?

**Comment by Koc** [comment]
@SebastianKrupinski I can't find a ticket for that issue

File: src/mixins/EditorMixin.js (hunk 1 above)
Comment (GVodyanov) [reply src/mixins/EditorMixin.js:408]: I think @hamza221 worked on this and should maybe know

**Comment by Aveyron-RetD** [comment]
it will close https://github.com/nextcloud/calendar/issues/7113

**Comment by Koc** [comment]
@mejo- @Aveyron-RetD any chance to merge it then?
