### PR TITLE
Fix new events disappearing from the grid

### LINKED ISSUE #2968: The time-slot I select while in day/week preview, disappears when i click the event title
### Steps to reproduce
1. Change the view to week or day
2. Select a time you want
3. Click anywhere on the popup

### Expected behaviour
The time i select shows all the time

### Actual behaviour
The time i select goes away
time_week_day

### Calendar app
**Calendar app version:** master

### PR DESCRIPTION
**Pull request by st3iny**
Fixes #2968

New events disappear from the grid when a user switches from the simple to the sidebar editor. Now, the event stays until the user either saves it or discards it by closing either editor.

# TODO
* [x] Fix tests
* [x] Fix popup position

### CODE REVIEW

**Comment by GretaD** [comment]
this fixes the problem, but breaks the popup position, it is always shown top-left. I tried with brave and FF

**Comment by st3iny** [comment]
Soo I really did break the popup. I'll investigate.

**Comment by st3iny** [comment]
@GretaD I finally fixed the popover position bug. Please test it again :)

File: src/components/CalendarGrid.vue [hunk 1]
```diff
@@ -220,6 +220,19 @@ export default {
 			}
 		}, 1000)
 
+		// Trigger the select event programmatically on initial page load to show the new event
+		// in the grid.
+		this.$nextTick(() => {
```
Comment (tcitworld) [inline src/components/CalendarGrid.vue:225]: Using `await this.$nextTick();` instead of the callback *should* work.

File: src/components/CalendarGrid.vue [hunk 2]
```diff
@@ -220,6 +220,19 @@ export default {
...
+			if (['NewPopoverView', 'NewSidebarView'].includes(this.$route.name)) {
+				const calendarApi = this.$refs.fullCalendar.getApi()
+				calendarApi.select({
+					start: new Date(parseInt(this.$route.params.dtstart) * 1000),
```
Comment (tcitworld) [inline src/components/CalendarGrid.vue:229]: No handling for when an invalid date is created?

File: src/components/CalendarGrid.vue (hunk 1 above)
Comment (st3iny) [reply src/components/CalendarGrid.vue:225]: Neat! I didn't know that it returns a promise.

File: src/components/CalendarGrid.vue (hunk 2 above)
Comment (st3iny) [reply src/components/CalendarGrid.vue:229]: FC has an internal sanity check and does not propagate the select event to our handler if the dates are invalid. I just tested this.

Comment (st3iny) [reply src/components/CalendarGrid.vue:229]: PS: I still committed the check because why not :D

File: src/components/CalendarGrid.vue [hunk 3]
```diff
@@ -244,6 +244,22 @@ export default {
 
 			next()
 		})
+
+	  // Trigger the select event programmatically on initial page load to show the new event
+	  // in the grid. Wait for the next tick because the ref isn't available right away.
+	  await this.$nextTick()
+		if (['NewPopoverView', 'NewSidebarView'].includes(this.$route.name)) {
```
Comment (tcitworld) [inline src/components/CalendarGrid.vue:251]: indentation is off

Comment (st3iny) [reply src/components/CalendarGrid.vue:251]: Good catch

**Review by ChristophWurst — APPROVED** [review]

**Comment by szaimen** [comment]
Is this backportable?

**Comment by ChristophWurst** [comment]
let's find out
