### PR TITLE
Fix category selection

### LINKED ISSUE #3802: Custom categories broke event editor
### Steps to reproduce
1. create or open an event 
2. fill what is needed
3. type a custom category
4. click on this custom category to add it

### Expected behaviour
The custom category is added (Worked great until some days ago)

### Actual behaviour
Cannot click on the custom category, the category remain display waiting to be validate and cannot do anything in the editor. When trying to close the event curently edited the panel remain open but the content disappear and a wheel turn until closing the tab ou windows 

### Calendar app
**version 3.0.1**

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, iOS Calendar)

### Client configuration
**Browser: Firefox 94**

**Operating system:** Windows 10, Ubuntu

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MySQL

**PHP version:** (e.g. 7.4)

**Nextcloud Version:** 22.2.3

**Updated from an older installed version or fresh install:** updated

**List of activated apps:**
- accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.13.0
  - calendar: 3.0.1
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - collectives: 0.16.22
  - comments: 1.12.0
  - contacts: 4.0.6
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.5
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.4.0
  - groupfolders: 10.0.0
  - guests: 2.1.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.11.1
  - metadata: 0.15.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - rainloop: 7.1.2
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - sharingpath: 0.4.3
  - spreed: 12.2.2
  - support: 1.5.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0

**Nextcloud configuration:**
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": REMOVED,
        "Overwriteprotocol": "http",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "35242",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maxZipInputSize": 209715200,
        "allowZipDownload": true,
        "loglevel": 0,
        "maintenance": false,
        "defaultapp": "files",
        "enable_avatars": true,
        "appcodechecker": false,
        "updatechecker": true,
        "updater.release.channel": "stable",
        "integrity.check.disabled": true,
        "check_for_working_htaccess": true,
        "check_for_working_wellknown_setup": true,
        "gs.federation": "global",
        "filesystem_check_changes": 1,
        "theme": "",
        "remember_login_cookie_lifetime": 604800,
        "session_lifetime": 21600,
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "trusted_domains": [
            REMOVED
        ],
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "allow_user_to_change_display_name": true,
        "knowledgebaseenabled": true,
        "filelocking.enabled": true,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "occweb",
            "groupfolders",
            "twofactor_nextcloud_notification",
            "spreed",
            "files_downloadactivity",
            "sharingpath"
        ],
        "mysql.utf8mb4": true

Thanks for your replies

### LINKED ISSUE #3939: Same event category can be added multiple times, but cannot be removed
### Steps to reproduce
1. Create an event and edit it via right sidebar.
2. Jump into category selection.
3. Click twice on the checkmark left of one category name.

### Expected behaviour
The first click should add the category to the event. The second click should remove it from the list of currently selected categories.

### Actual behaviour
The category is added twice to the category list. I could not find a way to remove categories.

### Calendar app
**Calendar app version:** 3.0.5 (see apps admin page, e.g. 2.0.1)

**CalDAV-clients used:** none (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** Firefox 96.0.3 (64-Bit) (e.g. Firefox 48)

**Operating system:** Debian 11 (e.g. Arch Linux)

### Server configuration

**Operating system:** Debian 11 (e.g. Debian 8)

**Web server:** Apache (e.g. Apache, Nginx,...)

**Database:** MariaDB (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** 8.0 (e.g. 7.0.3)

**Nextcloud Version:** 22.2.0, 24.0.0 dev (see admin page, e.g. 17.0.2)

**Updated from an older installed version or fresh install:** fresh install

#### Browser log
```
06:44:17.479
GEThttp://127.0.0.1/index.php/apps/calendar/dayGridMonth/now/edit/sidebar/L3JlbW90ZS5waHAvZGF2L2NhbGVuZGFycy9BZG1pbi9wZXJzb25hbC02LzVDMkEwN0QyLTM1QkYtNDAzNy05QTdDLTg2ODIxOUJBMTMwQi5pY3M=/1644235220
[[HTTP/1.1 200 OK 97ms]]()

06:44:17.735
GEThttp://127.0.0.1/dist/core-common.js?v=1e40617f-0
[[HTTP/1.1 200 OK 384ms]]()

06:44:17.740
GEThttp://127.0.0.1/dist/core-main.js?v=1e40617f-0
[[HTTP/1.1 200 OK 6ms]]()

06:44:17.767
GEThttp://127.0.0.1/dist/core-files_fileinfo.js?v=1e40617f-0
[[HTTP/1.1 200 OK 0ms]]()

06:44:17.792
GEThttp://127.0.0.1/dist/core-files_client.js?v=1e40617f-0
[[HTTP/1.1 200 OK 0ms]]()

06:44:17.800
GEThttp://127.0.0.1/index.php/js/core/merged-template-prepend.js?v=1e40617f-0
[[HTTP/1.1 304 Not Modified 121ms]]()

06:44:17.823
GEThttp://127.0.0.1/core/js/backgroundjobs.js?v=1e40617f-0
[[HTTP/1.1 200 OK 28ms]]()

06:44:17.826
GEThttp://127.0.0.1/dist/core-unified-search.js?v=1e40617f-0
[[HTTP/1.1 200 OK 2ms]]()

06:44:17.840
GEThttp://127.0.0.1/dist/accessibility-accessibilityoca.js?v=1e40617f-0
[[HTTP/1.1 200 OK 1ms]]()

06:44:17.842
GEThttp://127.0.0.1/dist/files_sharing-main.js?v=1e40617f-0
[[HTTP/1.1 200 OK 0ms]]()

06:44:17.851
GEThttp://127.0.0.1/apps/theming/js/theming.js?v=1e40617f-0
[[HTTP/1.1 304 Not Modified 0ms]]()

06:44:17.854
GEThttp://127.0.0.1/dist/user_status-menu.js?v=1e40617f-0
[[HTTP/1.1 200 OK 1ms]]()

06:44:17.856
GEThttp://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0
[[HTTP/1.1 200 OK 271ms]]()

06:44:17.861
GEThttp://127.0.0.1/apps/dashboard/img/dashboard.svg?v=1e40617f
[[HTTP/1.1 304 Not Modified 12ms]]()

06:44:17.865
GEThttp://127.0.0.1/apps/files/img/app.svg?v=1e40617f
[[HTTP/1.1 304 Not Modified 6ms]]()

06:44:17.871
GEThttp://127.0.0.1/apps/calendar/img/calendar.svg?v=1e40617f
[[HTTP/1.1 304 Not Modified 5ms]]()

06:44:17.877
GEThttp://127.0.0.1/apps/user_status/img/app.svg?v=1e40617f
[[HTTP/1.1 304 Not Modified 1ms]]()

06:44:17.878
GEThttp://127.0.0.1/apps/settings/img/apps.svg?v=1e40617f
[[HTTP/1.1 304 Not Modified 0ms]]()

06:44:17.878
GEThttp://127.0.0.1/apps/settings/img/admin.svg?v=1e40617f
[[HTTP/1.1 304 Not Modified 0ms]]()

06:44:17.885
GEThttp://127.0.0.1/apps/settings/img/users.svg?v=1e40617f
[[HTTP/1.1 304 Not Modified 1ms]]()

06:44:17.886
GEThttp://127.0.0.1/apps/settings/img/help.svg?v=1e40617f
[[HTTP/1.1 304 Not Modified 0ms]]()

06:44:17.887
GEThttp://127.0.0.1/core/img/actions/logout.svg?v=1e40617f
[[HTTP/1.1 304 Not Modified 0ms]]()

06:44:17.888
GEThttp://127.0.0.1/index.php/avatar/Admin/32?v=0
[[HTTP/1.1 304 Not Modified 201ms]]()

06:44:18.139
GEThttp://127.0.0.1/index.php/js/core/merged-template-prepend.js?v=1e40617f-0

06:44:18.372 No OC found [core-common.js:2:3648084](http://127.0.0.1/dist/core-common.js?v=1e40617f-0)
06:44:18.393 Proxying an event bus of version 2.1.1 with 1.3.0 [core-common.js:2:84005](http://127.0.0.1/dist/core-common.js?v=1e40617f-0)
06:44:18.394 JQMIGRATE: Migrate is installed, version 3.3.2 [core-common.js:2:4669799](http://127.0.0.1/dist/core-common.js?v=1e40617f-0)
06:44:18.434 Proxying an event bus of version 2.1.1 with 1.3.0 [core-common.js:2:84005](http://127.0.0.1/dist/core-common.js?v=1e40617f-0)
06:44:18.460
XHRGEThttp://127.0.0.1/ocs/v2.php/search/providers?from=/apps/calendar/dayGridMonth/now/edit/sidebar/L3JlbW90ZS5waHAvZGF2L2NhbGVuZGFycy9BZG1pbi9wZXJzb25hbC02LzVDMkEwN0QyLTM1QkYtNDAzNy05QTdDLTg2ODIxOUJBMTMwQi5pY3M=/1644235220
[[HTTP/1.1 200 OK 81ms]]()

06:44:18.478 Proxying an event bus of version 2.1.1 with 1.3.0 [core-common.js:2:84005](http://127.0.0.1/dist/core-common.js?v=1e40617f-0)
06:44:18.515
XHRPUThttp://127.0.0.1/index.php/apps/user_status/heartbeat
[[HTTP/1.1 200 OK 69ms]]()

06:44:18.587 Proxying an event bus of version 2.1.1 with 1.3.0 [calendar-main.js:2:28817](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:18.701 [INFO] calendar: 
Initial settings:
	- AppVersion: 3.0.5
	- EventLimit: true
	- FirstRun: true
	- ShowWeekNumbers: false
	- ShowTasks: true
	- ShowWeekends: true
	- SkipPopover: false
	- SlotDuration: 00:30:00
	- DefaultReminder: none
	- TalkEnabled: false
	- TasksEnabled: false
	- Timezone: automatic
 <unavailable> [calendar-main.js:2:266756](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:18.705
XHRPROPFINDhttp://127.0.0.1/remote.php/dav/
[[HTTP/1.1 207 Multi-Status 79ms]]()

06:44:18.745 [DEBUG] @nextcloud/vue: Using version 2.2019c of the timezone database <unavailable> [calendar-main.js:2:266691](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:19.094 @nextcloud/calendar-js app is using version 2.2019c of the timezone database [calendar-main.js:2:242130](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:19.383 Fallback to locale en [calendar-main.js:2:4850324](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:19.383 [INFO] calendar: Updated moment locale: en <unavailable> [calendar-main.js:2:266756](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:19.388
GEThttp://127.0.0.1/index.php/apps/theming/icon/calendar?v=0
[[HTTP/1.1 200 OK 0ms]]()

06:44:19.393 session heartbeat polling started [core-main.js:2:54207](http://127.0.0.1/dist/core-main.js?v=1e40617f-0)
06:44:19.393
GEThttp://127.0.0.1/index.php/apps/theming/favicon/calendar?v=0
[[HTTP/1.1 200 OK 0ms]]()

06:44:19.396 This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[core-common.js:2:4376350](http://127.0.0.1/dist/core-common.js?v=1e40617f-0)
06:44:19.397 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 [core-main.js:2:67283](http://127.0.0.1/dist/core-main.js?v=1e40617f-0)
06:44:19.435 [DEBUG] unified-search: Unified Search initialized with the following providers <unavailable> [core-common.js:2:344734](http://127.0.0.1/dist/core-common.js?v=1e40617f-0)
06:44:19.439
XHRGEThttp://127.0.0.1/cron.php
[[HTTP/1.1 200 OK 126ms]]()

06:44:19.485
XHRPROPFINDhttp://127.0.0.1/remote.php/dav/principals/users/Admin/
[[HTTP/1.1 207 Multi-Status 136ms]]()

06:44:19.700 [DEBUG] calendar: Current user principal is /remote.php/dav/principals/users/Admin/ <unavailable> [calendar-main.js:2:266691](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:19.706
XHRPROPFINDhttp://127.0.0.1/remote.php/dav/calendars/Admin/
[[HTTP/1.1 207 Multi-Status 140ms]]()

06:44:19.862 calendar home scanned <unavailable> <unavailable> [calendar-main.js:2:4922312](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:19.918
XHRREPORThttp://127.0.0.1/remote.php/dav/calendars/Admin/personal-6/
[[HTTP/1.1 207 Multi-Status 86ms]]()

06:44:19.994 [DEBUG] calendar: calendars and trash bin loaded <unavailable> [calendar-main.js:2:266691](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:19.998
XHRPROPFINDhttp://127.0.0.1/remote.php/dav/calendars/Admin/personal-6/5C2A07D2-35BF-4037-9A7C-868219BA130B.ics
[[HTTP/1.1 207 Multi-Status 83ms]]()

06:44:20.163
XHRGEThttp://127.0.0.1/apps/calendar/img/illustrations/no_data.svg
[[HTTP/1.1 200 OK 0ms]]()

06:44:20.506 [DEBUG] calendar: Option render <unavailable> 15 [calendar-main.js:2:266691](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:20.533 [INFO] calendar: fetching suggestions for 0 attendees <unavailable> [calendar-main.js:2:266756](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:20.813 [DEBUG] calendar: availability of room suggestions fetched <unavailable> [calendar-main.js:2:266691](http://127.0.0.1/apps/calendar/js/calendar-main.js?v=1e40617f-0)
06:44:20.832
XHRREPORThttp://127.0.0.1/remote.php/dav/calendars/Admin/personal-6/
[[HTTP/1.1 207 Multi-Status 83ms]]()
```

Likely related to #3802.

### PR DESCRIPTION
**Pull request by max65482**
This PR sketches a possible solution to fixes #3939 and fixes #3802. However, there might be better/easier ways to fix this.

The underlying issue was a binding problem in the Multiselect controls: The bound data source (the event's categories) is changed in the `selectValue` handler. As far as I understand, this causes rerendering inside the handler. That is why the selection does not complete and categories can be selected multiple times.

This is solved by having the Multiselect controls work on their own data (`value`). The event's categories are synchronized on startup and upon selection/deselection.

However, this proposal needs more attention. The following problems need to be addressed:
* After opening an event, the category list is not collapsed, but squeezed in.
* See warnings in browsler log.
* See compile output.

### CODE REVIEW

File: src/components/Editor/Properties/PropertySelectMultiple.vue [hunk 1]
```diff
@@ -86,6 +87,14 @@ import { getLocale } from '@nextcloud/l10n'
 import InformationVariant from 'vue-material-design-icons/InformationVariant.vue'
 
 export default {
+	mounted() {
+		for (const value of this.calendarObjectInstance.categories) {
+			const option = this.options.find(option => option.value === value)
+			if (option) {
+				this.value.push(option)
```
Comment (tcitworld) [inline src/components/Editor/Properties/PropertySelectMultiple.vue:94]: You're not supposed to modify props, as the linter says.

**Comment by max65482** [comment]
> After opening an event, the category list is not collapsed, but squeezed in.

Does somebody know how to fix this?

grafik

It's more of a glitch. After resizing the browser window, categories are properly collapsed.

The bug didn't come up with my changes, but existed before. This might be a good place to fix it, though.

**Comment by max65482** [comment]
I think it is worth reviewing this PR even without a fix for the cosmetic issue from my previous comment. It already fixes the functional limitations.

**Review by JuliaKirschenheuter — APPROVED** [review]
works!
Please run ``` npm run lint:fix```

**Comment by max65482** [comment]
> please update / rebase main branch
> please merge all commits all together

Done!

> Please run npm run lint:fix

returned
```
/var/www/html/apps/calendar/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:278
  })() ?? jsdoc.source.findIndex(({
        ^
SyntaxError: Unexpected token '?'
```

However, I think I fixed the relevant linter complain manually (in-line `v-if`).

File: src/components/Editor/Properties/PropertySelectMultiple.vue [hunk 2]
```diff
@@ -100,24 +100,51 @@ export default {
...
+	},
 	computed: {
+		selection: {
+			get() {
+				return this.selectionData
+			},
+			set(newValue) {
+				this.selectionData = newValue
+			},
+		},
```
Comment (st3iny) [inline src/components/Editor/Properties/PropertySelectMultiple.vue:116]:
```suggestion
```

This computed property is obsolete. Instead, `this.selectionData` should be used.

File: src/components/Editor/Properties/PropertySelectMultiple.vue [hunk 3]
```diff
@@ -32,19 +32,19 @@
 		<div class="property-select-multiple__input"
 			:class="{ 'property-select-multiple__input--readonly': isReadOnly }">
 			<Multiselect v-if="!isReadOnly"
+				v-model="selection"
```
Comment (st3iny) [inline src/components/Editor/Properties/PropertySelectMultiple.vue:35]:
```suggestion
				v-model="selectionData"
```

**Review by st3iny — CHANGES_REQUESTED** [review]
Thank you for the PR!

Tested and works. I left some minor feedback on your code.

File: src/components/Editor/Properties/PropertySelectMultiple.vue (hunk 2 above)
Comment (max65482) [reply src/components/Editor/Properties/PropertySelectMultiple.vue:116]: This caused linter complaints (see review from @tcitworld above).

Comment (max65482) [reply src/components/Editor/Properties/PropertySelectMultiple.vue]: Ok, linter behavior seems to have changed. Removing the computed property seems fine.

**Comment by max65482** [comment]
Ready to merge from my perspective.

**Comment by st3iny** [comment]
> Ready to merge from my perspective.

Awesome. I'll have another look at the PR soon.

**Comment by Kayoku** [comment]
Hi, I can't understand this is not still merged....
We can't use category in calendar, this is a main feature of the tools. (https://github.com/nextcloud/calendar/issues/3802) This is really a mess for some Teams which think about leaving Nextcloud because of this kind of regression. I'm pretty sad :(

**Comment by ChristophWurst** [comment]
I'm well aware @Kayoku. Currently there are a bunch of high prio bugs we need to address. This is one of them: https://github.com/orgs/nextcloud/projects/61/views/9. We will have a look soon.

**Review by st3iny — APPROVED** [review]
Tested and works.

**Comment by nderambure** [comment]
Thx you for this !
