### PR TITLE
catch more GuzzleHttp exceptions

### LINKED ISSUE #110: Handle bad certificat errors in webcal remote calendars
Details of the error : 

<details>

```
Exception: {"Exception":"GuzzleHttp\\Exception\\RequestException",
"Message":"Error creating resource: [message] fopen(): Peer certificate CN=`*.userpoint.fi' did not match expected CN=`www.webcal.fi'\n[file] \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Client\/StreamHandler.php\n[line] 406\n
[message] fopen(): Failed to enable crypto\n[file] \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Client\/StreamHandler.php\n[line] 406\n
[message] fopen(https:\/\/www.webcal.fi\/cal.php?id=49&amp;rid=ics&amp;wrn=0&amp;wp=12&amp;wf=55): failed to open stream: operation failed\n[file] \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Client\/StreamHandler.php\n[line] 406\n[message] Undefined variable: http_response_header\n[file] \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Client\/StreamHandler.php\n[line] 407","Code":0,
"Trace":"#0 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(104): GuzzleHttp\\Exception\\RequestException::wrapException(Object(GuzzleHttp\\Message\\Request), Object(GuzzleHttp\\Ring\\Exception\\RingException))\n
#1 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(132): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n
#2 \/var\/www\/nextcloud\/3rdparty\/react\/promise\/src\/FulfilledPromise.php(25): GuzzleHttp\\RequestFsm->GuzzleHttp\\{closure}(Array)\n
#3 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Future\/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)\n
#4 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Message\/FutureResponse.php(43): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\n
#5 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(135): GuzzleHttp\\Message\\FutureResponse::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))\n
#6 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php(165): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n
#7 \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php(125): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Message\\Request))\n#8 \/var\/www\/nextcloud\/lib\/private\/Http\/Client\/Client.php(137): GuzzleHttp\\Client->get('https:\/\/www.web...', Array)\n
#9 \/var\/www\/nextcloud\/apps\/calendar\/controller\/proxycontroller.php(61): OC\\Http\\Client\\Client->get('https:\/\/www.web...', Array)\n
#10 [internal function]: OCA\\Calendar\\Controller\\ProxyController->proxy('https:\/\/www.web...')\n
#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n
#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Calendar\\Controller\\ProxyController), 'proxy')\n
#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(127): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Calendar\\Controller\\ProxyController), 'proxy')\n
#14 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ProxyController', 'proxy', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n
#15 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n
#16 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(298): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n
#17 \/var\/www\/nextcloud\/lib\/base.php(994): OC\\Route\\Router->match('\/apps\/calendar\/...')\n
#18 \/var\/www\/nextcloud\/index.php(40): OC::handleRequest()\n
#19 {main}","File":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Exception\/RequestException.php","Line":51}7
```

</details>

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #110

### CODE REVIEW

File: controller/proxycontroller.php [hunk 1]
```diff
@@ -65,9 +86,27 @@ public function proxy($url) {
...
 			$error_code = $e->getResponse()->getStatusCode();
-			$response = new JSONResponse();
-			$response->setStatus($error_code);
+			$message = $e->getMessage();
+
+			$this->logger->debug($message);
+			$response = new JSONResponse([
+				'message' => $message,
+				'proxy_code' => $error_code
+			], Http::STATUS_IM_A_TEAPOT);
```
Comment (tcitworld) [inline controller/proxycontroller.php]: Not saying I didn't smile, but maybe there could be a more helping http code here. 🙂

**Comment by georgehrke** [comment]
please review @raghunayyar @tcitworld

**Comment by tcitworld** [comment]
:+1:
