### PR TITLE
Fix appointment details styling when in a small screen 

### LINKED ISSUE #4614: Appointments moible view is cutting of information
### Steps to reproduce

image

### Expected behavior

Full screen modal, content is ordered one below the other
cc @nextcloud/designers 

### Actual behaviour

Content doesn't adjust to screen width

### Calendar app version

v4.0.0-rc.1

### CalDAV-clients used

Web

### Browser

Chrome

### Client operating system

Ubuntu

### Server operating system

c.nc

### Web server

_No response_

### Database engine version

_No response_

### PHP engine version

_No response_

### Nextcloud version

_No response_

### Updated from an older installed version or fresh install

_No response_

### List of activated apps

_No response_

### Nextcloud configuration

_No response_

### Web server error log

_No response_

### Log file

_No response_

### Browser log

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #4614 
after
Screenshot from 2022-10-18 14-44-42

### CODE REVIEW

**Review by st3iny — COMMENTED** [review]
Looks weird on normal resolutions now:
image

You could try using `flex-wrap: wrap`.

File: src/components/Appointments/AppointmentDetails.vue [hunk 1]
```diff
@@ -148,6 +148,7 @@ export default {
 	display: flex;
 	flex-direction: row;
 	padding: 30px;
+  flex-wrap: wrap;
```
Comment (st3iny) [inline src/components/Appointments/AppointmentDetails.vue:151]:
```suggestion
	flex-wrap: wrap;
```

Indentation ;)

**Review by st3iny — APPROVED** [review]
Beautiful! Tested and works.
