### PR TITLE
Fix: move state init to a service

### LINKED ISSUE #6076: Button to create Talk room for appointment never shows up states TalkEnabled: false in browser console
### Steps to reproduce

1. Create new event
2. Add attendees

### Expected behavior

The "Create a new Talk room" button shows up below the "Find a time" button.

### Actual behaviour

No button shows up

### Calendar app version

4.7.6

### CalDAV-clients used

n/a

### Browser

Latest Chrome and Firefox

### Client operating system

Fedora Linux, Windows 10, Windows 11

### Server operating system

Nextcloud-AIO on Debian 12

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

29.0.2

### Updated from an older installed version or fresh install

None

### List of activated apps

```Text
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - app_api: 2.6.0
  - assistant: 1.1.0
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.6
  - call_summary_bot: 1.1.1
  - camerarawpreviews: 0.8.5
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_antivirus: 5.5.5
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_fulltextsearch: 29.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_retention: 1.18.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - fileslibreofficeedit: 1.1.0
  - firstrunwizard: 2.18.0
  - flow_notifications: 1.9.0
  - forms: 4.2.4
  - fulltextsearch: 29.0.0
  - fulltextsearch_elasticsearch: 29.0.1
  - groupfolders: 17.0.1
  - impersonate: 1.16.0
  - integration_giphy: 1.0.10
  - integration_google: 2.2.0
  - integration_openai: 2.0.1
  - integration_youtube: 0.2.1
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.7.1
  - maps: 1.4.0
  - memegen: 1.0.8
  - memories: 7.3.1
  - nextcloud-aio: 0.6.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - notify_push: 0.6.12
  - oauth2: 1.17.0
  - oidc: 0.9.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - previewgenerator: 5.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recognize: 7.0.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.3
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - sociallogin: 5.6.5
  - socialsharing_email: 3.1.0
  - spreed: 19.0.3
  - stt_helper: 1.1.1
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tables: 0.7.3
  - tasks: 0.16.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - twofactor_webauthn: 1.4.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflow_ocr: 1.29.0
  - workflowengine: 2.11.0
Disabled:
  - encryption: 2.17.0
  - user_ldap: 1.20.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "cloud.maas-opleidingen.nl",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.maas-opleidingen.nl"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "29.0.2.2",
        "overwrite.cli.url": "https:\/\/cloud.maas-opleidingen.nl\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": "10485760",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "jpeg_quality": 60,
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "0": "OC\\Preview\\Imaginary"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": "30",
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "htaccess.RewriteBase": "\/",
        "files_external_allow_create_new_local": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "default_phone_region": "NL",
        "maintenance": false,
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/exiftool-amd64-musl",
        "memories.qsv": true,
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.disable": false,
        "memories.vod.vaapi": true,
        "memories.vod.nvenc": false,
        "memories.vod.nvenc.scale": "npp",
        "memories.vod.nvenc.temporal_aq": true,
        "updatedirectory": "\/nc-updater",
        "updater.release.channel": "stable",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "davstorage.request_timeout": 3600,
        "dbpersistent": false,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appsallowlist": false,
        "maintenance_window_start": 100,
        "preview_imaginary_key": "***REMOVED SENSITIVE VALUE***",
        "memories.db.triggers.fcu": true,
        "auth.bruteforce.protection.enabled": true,
        "ratelimit.protection.enabled": true,
        "memories.gis_type": 2
    }
}
```

### Web server error log

```Text
Nothing relevant to see here.
```

### Log file

_No response_

### Browser log

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
Fix https://github.com/nextcloud/assistant/issues/92#issuecomment-2202580698 
Fix #6076

### CODE REVIEW

File: lib/Listener/CalendarReferenceListener.php [hunk 1]
```diff
@@ -9,104 +9,28 @@
...
 	public function __construct(
-		IInitialState $initialStateService,
-		IAppManager $appManager,
-		IConfig $config,
-		IAppData $appData,
-		CompareVersion $compareVersion,
-	) {
-		$this->config = $config;
+		private CalendarInitialStateService $initialStateService) {
 		$this->initialStateService = $initialStateService;
```
Comment (miaulalala) [inline lib/Listener/CalendarReferenceListener.php:26]: this can go
```suggestion
```

File: lib/Service/CalendarInitialStateService.php [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+
+	}
+
+	/**
+	 * Load the main calendar page
+	 *
+	 * @NoAdminRequired
+	 * @NoCSRFRequired
+	 *
+	 * @return TemplateResponse
```
Comment (miaulalala) [inline lib/Service/CalendarInitialStateService.php:42]: wrong return type?

File: lib/Service/CalendarInitialStateService.php [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+		$this->userId = $userId;
+
+	}
+
+	/**
+	 * Load the main calendar page
+	 *
+	 * @NoAdminRequired
+	 * @NoCSRFRequired
+	 *
```
Comment (miaulalala) [inline lib/Service/CalendarInitialStateService.php:41]: Services don't need that annotation

File: lib/Controller/ViewController.php [hunk 4]
```diff
@@ -8,26 +8,21 @@
...
 
 class ViewController extends Controller {
 	/** @var IConfig */
 	private $config;
 
-	/** @var AppointmentConfigService */
-	private $appointmentConfigService;
-
 	/** @var IInitialState */
 	private $initialStateService;
```
Comment (miaulalala) [inline lib/Controller/ViewController.php:27]:
```suggestion
```

File: lib/Controller/ViewController.php [hunk 5]
```diff
@@ -8,26 +8,21 @@
...
-use function in_array;
 
 class ViewController extends Controller {
 	/** @var IConfig */
 	private $config;
 
-	/** @var AppointmentConfigService */
-	private $appointmentConfigService;
-
 	/** @var IInitialState */
```
Comment (miaulalala) [inline lib/Controller/ViewController.php:26]:
```suggestion
```

**Review by miaulalala — CHANGES_REQUESTED** [review]

File: lib/Listener/CalendarReferenceListener.php [hunk 6]
```diff
@@ -9,104 +9,28 @@
 
 namespace OCA\Calendar\Listener;
 
-use OC\App\CompareVersion;
 use OCA\Calendar\AppInfo\Application;
-use OCP\App\IAppManager;
-use OCP\AppFramework\Services\IInitialState;
+use OCA\Calendar\Service\CalendarInitialStateService;
+
```
Comment (miaulalala) [inline lib/Listener/CalendarReferenceListener.php:14]:
```suggestion
```

File: lib/Service/CalendarInitialStateService.php [hunk 7]
```diff
@@ -0,0 +1,128 @@
...
+		private ?string $userId,
+	) {
+		$this->appName = $appName;
+		$this->config = $config;
+		$this->initialStateService = $initialStateService;
+		$this->appointmentConfigService = $appointmentConfigService;
+		$this->appManager = $appManager;
+		$this->compareVersion = $compareVersion;
+		$this->userId = $userId;
+
```
Comment (miaulalala) [inline lib/Service/CalendarInitialStateService.php:35]:
```suggestion
```

File: lib/Service/CalendarInitialStateService.php [hunk 8]
```diff
@@ -0,0 +1,128 @@
...
+	}
+
```
Comment (miaulalala) [inline lib/Service/CalendarInitialStateService.php:37]:
```suggestion
```

File: lib/Service/CalendarInitialStateService.php [hunk 9]
```diff
@@ -0,0 +1,128 @@
...
+		$this->initialStateService->provideInitialState('hide_event_export', $hideEventExport);
+		$this->initialStateService->provideInitialState('force_event_alarm_type', $forceEventAlarmType);
+		$this->initialStateService->provideInitialState('appointmentConfigs', $this->appointmentConfigService->getAllAppointmentConfigurations($this->userId));
+		$this->initialStateService->provideInitialState('disable_appointments', $disableAppointments);
+		$this->initialStateService->provideInitialState('can_subscribe_link', $canSubscribeLink);
+		$this->initialStateService->provideInitialState('show_resources', $showResources);
+		$this->initialStateService->provideInitialState('isCirclesEnabled', $isCirclesEnabled && $isCircleVersionCompatible);
+		$this->initialStateService->provideInitialState('publicCalendars', $publicCalendars);
+	}
+
```
Comment (miaulalala) [inline lib/Service/CalendarInitialStateService.php:105]:
```suggestion
```

**Review by miaulalala — COMMENTED** [review]
Sneaky

**Review by miaulalala — APPROVED** [review]
