### PR TITLE
fix: userAsAttendee failing in case of public links

### LINKED ISSUE #4011: Loading endless calendar event info panel if shared via a link and if a atendee is specified
### Steps to reproduce

1. Create calendar event, provide atendee
2. Share calendar via link
3. Open shared calendar via link, select event

Event withoud atendee info panel loads
without

Event with atendee loading endless
with

### Expected behavior

Shared calendar via link event with atendee show detailed event information in side panel

### Actual behaviour

Shared calendar via link event with atendee side panel loading endless

### Calendar app version

3.1.0

### CalDAV-clients used

_No response_

### Browser

Google Chrome 99.0.4844.51

### Client operating system

Windows 11

### Server operating system

Ubuntu server 20.04

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 7.4

### Nextcloud version

23.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - calendar: 3.1.0
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.8
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - drawio: 1.0.2
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - geoblocker: 0.5.4
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.3
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_external: 2.1.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - bruteforcesettings: 2.3.0
  - dashboard: 7.3.0
  - encryption
  - files_external
  - firstrunwizard: 2.12.0
  - richdocuments: 5.0.2
  - user_ldap
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "lv",
        "force_language": "lv",
        "default_locale": "lv_LV",
        "force_locale": "lv_LV",
        "default_phone_region": "LV",
        "simpleSignUpLink.shown": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "user_external",
            "drawio"
        ],
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "***REMOVED SENSITIVE VALUE***",
                    993,
                    "ssl",
                    "***REMOVED SENSITIVE VALUE***",
                    true,
                    false
                ]
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}
```

### Web server error log

_No response_

### Log file

_No response_

### Browser log

```Text
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'emailAddress')
    at getCurrentUserPrincipalEmail (principals.js:103:92)
    at r.forEachGetter.t._wrappedGetters.<computed> (vuex.esm.js:881:12)
    at Bn.<anonymous> (vuex.esm.js:140:12)
    at bn.get (vue.runtime.esm.js:4495:25)
    at bn.evaluate (vue.runtime.esm.js:4597:21)
    at Bn.getCurrentUserPrincipalEmail (vue.runtime.esm.js:4851:17)
    at Object.get [as getCurrentUserPrincipalEmail] (vuex.esm.js:671:39)
    at o.userAsAttendee (EditorMixin.js:234:61)
    at bn.get (vue.runtime.esm.js:4495:25)
    at bn.evaluate (vue.runtime.esm.js:4597:21)
```

### Additional info

_No response_

### LINKED ISSUE #4169: Events with ORGANIZER, detailed view stalled
### Steps to reproduce

1. Import an event from this ICS
```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
UID:328fe1be-f61b-4153-9138-586d63e8c3d5
DTSTART;VALUE=DATE:20220429
DTEND;VALUE=DATE:20220430
ORGANIZER;CN=John Smith:mailto:jsmith@example.com
SUMMARY:test
END:VEVENT
END:VCALENDAR
```
2. Try expanding the calendar item
3. The popup window opens but no details are shown

### Expected behavior

The details should be shown

### Actual behaviour

Spinning wheel forever

### Calendar app version

3.2.2

### CalDAV-clients used

_No response_

### Browser

Firefox-99, Chromium-100

### Client operating system

Gentoo Linux

### Server operating system

Gentoo Linux

### Web server

Apache

### Database engine version

_No response_

### PHP engine version

PHP 8.0

### Nextcloud version

23.0.4

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - calendar: 3.2.2
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - cospend: 1.4.6
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - bruteforcesettings: 2.2.0
  - encryption: 1.2.0
  - files_external: 1.1.2
  - issuetemplate: 0.7.0
  - user_ldap
```

### Nextcloud configuration

_No response_

### Web server error log

```Text
No error logs on the web server, but on the client side in the javascript console window there is an error pointing to `src/utils/attendee.js:29`
```

### Log file

_No response_

### Browser log

```Text
TypeError: t is undefined
    hx attendee.js:29
    userAsAttendee EditorMixin.js:234
    VueJS 3
    isViewedByAttendee EditorMixin.js:65
    VueJS 3
    bB EditSimple.vue:1
    VueJS 14
    e EditorMixin.js:657
    u dist.js:1
    _invoke dist.js:1
    S dist.js:1
    bx attendee.js:59
    o attendee.js:59
    promise callback*bx attendee.js:59
    o attendee.js:59
    promise callback*bx attendee.js:59
    o attendee.js:59
    yx attendee.js:59
    yx attendee.js:59
    e EditorMixin.js:657
    S vue-router.esm.js:290
    init vue-router.esm.js:392
    VueJS 19
    init vue-router.esm.js:3002
    init vue-router.esm.js:3002
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2401
    r vue-router.esm.js:2000
    r vue-router.esm.js:2004
    h vue-router.esm.js:2380
    confirmTransition vue-router.esm.js:2540
    e EditorMixin.js:636
    u dist.js:1
    _invoke dist.js:1
    S dist.js:1
    bx attendee.js:59
    o attendee.js:59
    yx attendee.js:59
    yx attendee.js:59
    beforeRouteEnter EditorMixin.js:634
    confirmTransition vue-router.esm.js:2535
    h vue-router.esm.js:2361
    r vue-router.esm.js:2003
    St vue-router.esm.js:2008
    confirmTransition vue-router.esm.js:2397
vue.runtime.esm.js:1897:4
    VueJS 17
    e EditorMixin.js:657
    u dist.js:1
    _invoke dist.js:1
    S dist.js:1
    bx attendee.js:59
    o attendee.js:59
    (Async: promise callback)
    bx attendee.js:59
    o attendee.js:59
    (Async: promise callback)
    bx attendee.js:59
    o attendee.js:59
    yx attendee.js:59
    yx attendee.js:59
    e EditorMixin.js:657
    S vue-router.esm.js:290
    init vue-router.esm.js:392
    VueJS 19
    init vue-router.esm.js:3002
    init vue-router.esm.js:3002
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2401
    r vue-router.esm.js:2000
    r vue-router.esm.js:2004
    h vue-router.esm.js:2380
    confirmTransition vue-router.esm.js:2540
    e EditorMixin.js:636
    u dist.js:1
    _invoke dist.js:1
    S dist.js:1
    bx attendee.js:59
    o attendee.js:59
    yx attendee.js:59
    yx attendee.js:59
    beforeRouteEnter EditorMixin.js:634
    confirmTransition vue-router.esm.js:2535
    h vue-router.esm.js:2361
    r vue-router.esm.js:2003
    St vue-router.esm.js:2008
    confirmTransition vue-router.esm.js:2397
```

### Additional info

checking if `uri` is undefined fixes the problem, however I'm surprised that uri is undefined in this case, because organizer is set, so the root problem is probably somewhere different.

### LINKED ISSUE #4706: Event details are NOT displayed when ORGANIZER prop is set and when the calendar is publicly shared
### Steps to reproduce

1. Create an event with an attendee (this will set the ORGANIZER as well)
2. Share the calendar via a public link
3. Visit the link as a GUEST (NOT LOGED-IN USER)
4. Click on the event 

### Expected behavior

image

### Actual behaviour

image

### Calendar app version

4.0.2 and earlier

### CalDAV-clients used

_No response_

### Browser

all

### Client operating system

ubuntu

### Server operating system

unbuntu

### Web server

_No response_

### Database engine version

MySQL

### PHP engine version

PHP 8.0

### Nextcloud version

25

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
see screen shot
```

### Nextcloud configuration

_No response_

### Web server error log

_No response_

### Log file

_No response_

### Browser log

```Text
vue.runtime.esm.js:3045 TypeError: Cannot read properties of undefined (reading 'emailAddress')
    at getCurrentUserPrincipalEmail (principals.js:103:92)
    at Be.r.forEachGetter.t._wrappedGetters.<computed> (vuex.esm.js:881:12)
    at tr.<anonymous> (vuex.esm.js:140:12)
    at t.get (vue.runtime.esm.js:3441:33)
    at t.evaluate (vue.runtime.esm.js:3542:27)
    at tr.getCurrentUserPrincipalEmail (vue.runtime.esm.js:5517:25)
    at Object.get [as getCurrentUserPrincipalEmail] (vuex.esm.js:671:39)
    at o.userAsAttendee (EditorMixin.js:234:61)
    at t.get (vue.runtime.esm.js:3441:33)
    at t.evaluate (vue.runtime.esm.js:3542:27)
```

### Additional info

ICS file for the event:
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//IDN nextcloud.com//Calendar app 4.0.1//EN
BEGIN:VEVENT
CREATED:20221029T192636Z
DTSTAMP:20221029T195639Z
LAST-MODIFIED:20221029T195639Z
SEQUENCE:3
UID:23adc7a4-c39c-4f47-b07b-8750b4bd4df8
DTSTART;VALUE=DATE:20221105
DTEND;VALUE=DATE:20221106
STATUS:CONFIRMED
SUMMARY:Organizer Test
ORGANIZER;CN=Admin25:mailto:sergey@reducted.com
ATTENDEE;CN=Cool Name;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PART
 ICIPANT;RSVP=TRUE;SCHEDULE-STATUS=1.1:mailto:someemail@example.com
END:VEVENT
END:VCALENDAR
```

### PR DESCRIPTION
**Pull request by fxmw11**
Check if the calendar is read-only first to avoid error due to non-existent currentUserPrincipal which causes endless loading on events with atendees in publicly shared calendars.
This should resolve issues #4011 and #4706

Closes #4011
Closes #4706
Closes #4169

### CODE REVIEW

File: src/views/EditSidebar.vue [hunk 1]
```diff
@@ -107,7 +107,7 @@
 				@update-end-timezone="updateEndTimezone"
 				@toggle-all-day="toggleAllDay" />
 
-			<InvitationResponseButtons v-if="isViewedByAttendee && userAsAttendee && !isReadOnly"
+			<InvitationResponseButtons v-if="!isReadOnly && isViewedByAttendee && userAsAttendee"
```
Comment (tcitworld) [inline src/views/EditSidebar.vue:110]: **issue:** This is a valid work around, but I prefer if you fixed instead `userAsAttendee` to handle `getCurrentUserPrincipalEmail` being undefined (so that it returns `null` straight away). Then there can be other uses of this computed property in other places without adding another check.
https://github.com/nextcloud/calendar/blob/a23e32dadda4a7751f6cc057a194df317cf19d56/src/mixins/EditorMixin.js#L229-L241

Also, the `userAsAttendee` shouldn't be needed, as `isViewedByAttendee` does basically that.

Comment (fxmw11) [reply src/views/EditSidebar.vue]: I see, we can simply move the read-only check to `userAsAttendee`.
Cleaned up the checks, hope it does not cause any other issues

File: src/views/EditSidebar.vue [hunk 2]
```diff
@@ -107,7 +107,7 @@
 				@update-end-timezone="updateEndTimezone"
 				@toggle-all-day="toggleAllDay" />
 
-			<InvitationResponseButtons v-if="isViewedByAttendee && userAsAttendee && !isReadOnly"
+			<InvitationResponseButtons v-if="isViewedByAttendee"
```
Comment (st3iny) [inline src/views/EditSidebar.vue:110]: Why remove the `userAsAttendee` check from here? Is this an oversight or on purpose?

File: src/views/EditSimple.vue [hunk 3]
```diff
@@ -142,7 +142,7 @@
 					:value="description"
 					@update:value="updateDescription" />
 
-				<InvitationResponseButtons v-if="isViewedByAttendee && userAsAttendee && !isReadOnly"
+				<InvitationResponseButtons v-if="isViewedByAttendee"
```
Comment (st3iny) [inline src/views/EditSimple.vue:145]: See above.

**Review by st3iny — COMMENTED** [review]
Looks good so far. I have two questions regarding the code.

File: src/views/EditSidebar.vue (hunk 2 above)
Comment (tcitworld) [reply src/views/EditSidebar.vue:110]: `isViewedByAttendee` already checks `userAsAttendee`

File: src/views/EditSidebar.vue (hunk 1 above)
Comment (tcitworld) [reply src/views/EditSidebar.vue]: Please still add handling for `this.$store.getters.getCurrentUserPrincipalEmail` being null, to avoid unexpected cases

Comment (fxmw11) [reply src/views/EditSidebar.vue]: getCurrentUserPrincipalEmail will fail if currentUserPrincipal is null so a simple check for `this.$store.state.principals.currentUserPrincipal === null` would be fine

I added a more general solution via an additional check in https://github.com/nextcloud/calendar/blob/8df701985580c213da0eb4b37abc3debae77381d/src/store/principals.js#L103

File: src/store/principals.js [hunk 4]
```diff
@@ -100,7 +100,7 @@ const getters = {
 	 * @param {object} state the store data
 	 * @return {string}
```
Comment (tcitworld) [inline src/store/principals.js:101]: **nitpick:** Not a JSDoc expert but I think that should work
```suggestion
	 * @return {string|undefined}
```

**Review by st3iny — APPROVED** [review]
Tested and works. Please squash all commits into a single one and we are ready to merge.

Thanks for your contribution!

**Comment by Blackclaws** [comment]
Looks good, applied the fix locally and it solved the issue. Would be great if this could make it into the next official release :)

**Comment by szaimen** [comment]
Conflicts?
