### PR TITLE
Handle disabled file_sharing app

### LINKED ISSUE #1967: Handle files_sharing app being disabled
Calendar share user search loads endlessly after user name typed in and wheel appears.
We have nextcloud with ldap_user backend and LDAP search filter and connection works as the user can be found through the contacts button on the upper right and occ ldap:check-user works:
Positive test (existing user):
```
$ occ ldap:check-user lollypop
The user is still available on LDAP.
```

Negative test (not existing user):
```
$ occ ldap:check-user lollypopd
The given user is not a recognized LDAP user.
```

Any idea so far?
Greetings,
   Lars

### Steps to reproduce
1. Click on share icon.
2. Enter Name of someone to share the calendar with.
3. Wait for next solar eclipse...

### Expected behaviour
The name from the LDAP adressbook should appear.

### Actual behaviour
Weel is going round and round and round and ... nothin happens.

### Calendar app
calendar: 2.0.1

### Client configuration
**Browser:**
- Chromium version 80.0.3987.87 (Official Build) snap (64-bit)
- Firefox 72.0.2 (64-bit)

**Operating system:** Linux / Ubuntu 19.10

### Server configuration

**Operating system**: Linux / Ubuntu 19.04

**Web server:** Apache/2.4.38

**Database:** MySQL 5.7.29-0ubuntu0.16.04.1-log

**PHP version:** PHP 7.2.24-0ubuntu0.19.04.2 (fpm-fcgi)

**Nextcloud Version:** version: 17.0.3.1

**Updated from an older installed version or fresh install:** Updated from 17.0.2

**List of activated apps:**

```
# occ app:list
Enabled:
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - metadata: 0.11.1
  - oauth2: 1.5.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - workflowengine: 1.7.0

```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "kalender.domain.de",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "overwrite.cli.url": "https:\/\/kalender.domain.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "defaultEntity": "University",
        "defaultName": "UNI",
        "defaultapp": "calendar",
        "defaultSlogan": "Cloud-Dienste unter Ihrer Kontrolle",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "theme": "mytheme",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auth.bruteforce.protection.enabled": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfilemode": 416,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "sort_groups_by_name": false,
        "tempdirectory": "\/var\/www\/tmp",
        "blacklisted_files": [
            ".htaccess"
        ],
        "cipher": "AES-256-CFB",
        "debug": false,
        "ldapUserCleanupInterval": 51,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "user_ldap.enable_medial_search": true,
        "skeletondirectory": "",
        "part_file_in_storage": true,
        "default_locale": "de_DE",
        "default_language": "de",
        "maintenance": false,
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "has_internet_connection": true,
        "data-fingerprint": "c2ecfd3cc03596e4fd43950daff35f4d"
    },
    "apps": {
        "accessibility": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": ""
        },
        "activity": {
            "enabled": "no",
            "installed_version": "2.9.1",
            "types": "filesystem"
        },
        "apporder": {
            "enabled": "no",
            "hidden": "[\"\/index.php\/apps\/files\/\"]",
            "installed_version": "0.9.0",
            "order": "[\"\/index.php\/apps\/files\/\",\"\/index.php\/apps\/calendar\/\",\"\/index.php\/apps\/contacts\/\"]",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "195381"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "checksum": {
            "enabled": "no",
            "installed_version": "0.4.4",
            "types": "filesystem"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.1.8",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1564066174.6108",
            "lastcron": "1581082207",
            "lastupdateResult": "[]",
            "lastupdatedat": "1581081074",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "941ec7f474b9a2a4102645e321b81145",
            "shareapi_allow_group_sharing": "yes",
            "shareapi_allow_links": "no",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_allow_share_dialog_user_enumeration": "yes",
            "shareapi_default_permission_cancreate": "yes",
            "shareapi_default_permissions": "31",
            "shareapi_enabled": "yes",
            "shareapi_exclude_groups": "no",
            "shareapi_only_share_with_group_members": "no",
            "theming.variables": "941ec7f474b9a2a4102645e321b81145",
            "updater.secret.created": "1576853306",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "generateBirthdayCalendar": "yes",
            "installed_version": "1.13.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendInvitations": "no",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "no",
            "installed_version": "0.8.0",
            "types": "dav"
        },
        "event_update_notification": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging,dav"
        },
        "federatedfilesharing": {
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "3000",
            "default_quota": "0 B",
            "enabled": "no",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_cmd_options": "",
            "av_host": "",
            "av_infected_action": "delete",
            "av_max_file_size": "-1",
            "av_mode": "socket",
            "av_path": "\/usr\/bin\/clamscan",
            "av_port": "0",
            "av_socket": "\/run\/clamav\/clamd.ctl",
            "av_stream_max_length": "26214400",
            "enabled": "no",
            "installed_version": "2.2.1",
            "types": "filesystem,dav"
        },
        "files_automatedtagging": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "no",
            "enabled": "no",
            "installed_version": "1.8.0",
            "types": "filesystem",
            "user_mounting_backends": "sftp,smb,\\OC\\Files\\Storage\\SFTP_Key,\\OC\\Files\\Storage\\SMB_OC"
        },
        "files_pdfviewer": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "no",
            "installed_version": "0.15.1",
            "types": ""
        },
        "files_sharing": {
            "enabled": "no",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.9.0",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "no",
            "installed_version": "1.9.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "2.5.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.3.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "no",
            "installed_version": "0.17.0",
            "types": ""
        },
        "metadata": {
            "enabled": "yes",
            "installed_version": "0.11.1",
            "types": ""
        },
        "news": {
            "enabled": "no",
            "installed_version": "14.1.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "no",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "notifications": {
            "enabled": "no",
            "installed_version": "2.4.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": ""
        },
        "previewgenerator": {
            "enabled": "no",
            "heightSize": "64 256",
            "installed_version": "2.2.0",
            "squareSizes": "32 64",
            "types": "filesystem",
            "widthSizes": "64 128"
        },
        "privacy": {
            "enabled": "no",
            "installed_version": "1.1.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "prevent_group_restriction"
        },
        "quickaccesssorting": {
            "enabled": "no",
            "installed_version": "1.0.2",
            "types": ""
        },
        "quota_warning": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "rainloop": {
            "enabled": "no",
            "installed_version": "6.0.4",
            "types": ""
        },
        "recommendations": {
            "enabled": "no",
            "installed_version": "0.4.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "no",
            "installed_version": "1.4.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "text": {
            "enabled": "no",
            "installed_version": "1.1.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "3",
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": ""
        },
        "updatenotification": {
            "bruteforcesettings": "1.5.0",
            "calendar": "2.0.0",
            "contacts": "3.1.8",
            "core": "17.0.2.1",
            "enabled": "[\"admin\"]",
            "installed_version": "1.7.0",
            "metadata": "0.11.1",
            "news": "14.1.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_ldap": {
            "background_sync_interval": "8585",
            "background_sync_offset": "0",
            "background_sync_prefix": "s01",
            "cleanUpJobOffset": "2350",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "s01_lastChange": "1581079602",
            "s01has_memberof_filter_support": "1",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "uid\nsn\ngivenname\nsamAccountName",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "DC=info,DC=domain,DC=de",
            "s01ldap_base_groups": "OU=Groups,OU=ou,DC=info,DC=domain,DC=de",
            "s01ldap_base_users": "OU=Users,OU=ou,DC=info,DC=domain,DC=de",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_default_ppolicy_dn": "",
            "s01ldap_display_name": "displayname",
            "s01ldap_dn": "info\\user",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "mail",
            "s01ldap_experienced_admin": "1",
            "s01ldap_expert_username_attr": "sAMAccountName",
            "s01ldap_expert_uuid_group_attr": "sAMAccountName",
            "s01ldap_expert_uuid_user_attr": "sAMAccountName",
            "s01ldap_ext_storage_home_attribute": "",
            "s01ldap_gid_number": "gidNumber",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "(objectCategory=group)",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "member",
            "s01ldap_groupfilter_groups": "datacenter\nuser",
            "s01ldap_groupfilter_objectclass": "group",
            "s01ldap_host": "ldaps:\/\/info.domain.de",
            "s01ldap_login_filter": "(&(&(|(objectclass=person))(|(|(memberof=CN=service_email,OU=services,OU=ou,DC=info,DC=domain,DC=de)(primaryGroupID=6728))))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "1",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "636",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_user_avatar_rule": "default",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "0",
            "s01ldap_userfilter_groups": "service_email",
            "s01ldap_userfilter_objectclass": "person",
            "s01ldap_userlist_filter": "(&(|(objectclass=person))(|(|(memberof=CN=service_OwnCloud,OU=services,OU=ou,DC=info,DC=domain,DC=de)(primaryGroupID=6728))))",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication",
            "updateAttributesInterval": "86400"
        },
        "viewer": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        }
    }
}
```

#### Web server error log (e.g. /var/log/apache)
```
Nothing special here.
```

#### Log file (data/nextcloud.log)
```
Nothing here at the moment when the lookup does not return.
```

#### Browser log
This is from the java console in Chromium:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'filter' of undefined
    at CalendarListItemSharingSearch.vue:197
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at AA (calendar.js?v=67bd37e1:2)
    at a (calendar.js?v=67bd37e1:2)
ze @ vue.runtime.esm.js:1888
Ze @ vue.runtime.esm.js:1879
Ue @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:1856
Promise.catch (async)
Qe @ vue.runtime.esm.js:1856
n @ vue.runtime.esm.js:2179
Qe @ vue.runtime.esm.js:1854
e.$emit @ vue.runtime.esm.js:3888
search @ vue-multiselect.min.js:1
dn.run @ vue.runtime.esm.js:4568
un @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Je @ vue.runtime.esm.js:1906
Promise.then (async)
He @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
dn.update @ vue.runtime.esm.js:4544
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
fn.set @ vue.runtime.esm.js:4631
deactivate @ vue-multiselect.min.js:1
blur @ vue-multiselect.min.js:1
Qe @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
o._wrapper @ vue.runtime.esm.js:6917
```
This is from java console in Firefox:
```
TypeError: "o is undefined"
    e CalendarListItemSharingSearch.vue:196
    c runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    AA calendar.js:2
    a calendar.js:2
vue.runtime.esm.js:1888:12
    VueJS 4
        ze
        Ze
        Ue
        Qe
```

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #1967

### CODE REVIEW

File: src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue [hunk 1]
```diff
@@ -195,6 +195,13 @@ export default {
 				return []
 			}
 
+			if (results.data.ocs.meta.status === 'failure') {
+				return []
+			}
+			if (!Array.isArray(results.data.ocs.data.circles)) {
```
Comment (tcitworld) [inline src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue]: What else can it return?

Comment (georgehrke) [reply src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue]: F782E963-9E73-47F0-A092-708045A01DFB

This endpoint provides plenty of things, including groups, addresses for remote sharing, etc. etc.

So it's just some sanity check, so we don't fail with some can not call filter on undefined error.
